// Help command - auto-generates help from all command modules
pub fn main(args: &str) {
    let args = args.trim();

    if !args.is_empty() {
        // Show help for specific command
        println!("Help for specific commands not yet implemented.");
        println!("Use 'help' to see all available commands.");
        return;
    }

    // Show all commands - auto-generated by the define_commands! macro
    println!("Available commands:");
    println!();

    // This function is auto-generated in cmd/mod.rs
    super::print_all_help();

    println!();
    println!("Output redirection:");
    println!("  <command> > <file>                - Redirect output to file");
    println!();
    println!("Script files:");
    println!("  Lines starting with # are comments");
    println!("  Empty lines are ignored");
}

pub fn help_text() -> &'static str {
    "help [command]                    - Show help for commands"
}
